server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/book?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true
      username: root
      password: xuchao123
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#  redis:
#    host: localhost
#    port: 6379
#    database: 0
#  thymeleaf:
#    cache: false
#    enabled: false
  mvc:
    view:
      # 页面默认前缀
      prefix: /WEB-INF/jsp/
      # 响应页面默认后缀
      suffix: .jsp
mybatis:
  mapperLocations: classpath:com.example.springboots.mapper/*.xml
  type-aliases-package: com.example.springboots.model